React
dev-academy-programme/concepts pull request #36
Opened 2017-04-14 08:06 UTC by tony-luisi

If merged, this pull request will:
1. Update the react concepts from using createClass to class extends
2. Add a section on JSX

2017-04-15 23:39 UTC, don-smith requested changes
Nice! So good to have these changes in place!

2017-04-15 23:39 UTC, don-smith commented on react/components.md
> +export default Header
I think I like `export default class Header extends React.Component {` over declaring and exporting the class separately (especially when we're exporting `default`). Thoughts?

2017-04-15 23:39 UTC, don-smith commented on react/event-delegation.md
> +In order to respond to user events, component functions can be bound to [virtual ] DOM events. In this example, a `addToCart` function in the `<ItemList />` component is called when a button is click
"In this example, **an** `addToCart` ..."

2017-04-15 23:39 UTC, don-smith commented on react/event-delegation.md
> +In order to respond to user events, component functions can be bound to [virtual ] DOM events. In this example, a `addToCart` function in the `<ItemList />` component is called when a button is click
There is also an extra space in `[virtual ]`

2017-04-15 23:39 UTC, don-smith commented on react/jsx.md
> +JSX is a syntax extension to javascript which can be thought of as a hybrid between HTML and javascript:
javascript ➡️ JavaScript

2017-04-15 23:39 UTC, don-smith commented on react/jsx.md
> +JSX is a syntax extension to javascript which can be thought of as a hybrid between HTML and javascript:
multiple instances in this file

2017-04-15 23:39 UTC, don-smith commented on react/jsx.md
> +      <input type="text" name="input"> // Doesn't self close
self-close (just for consistency)?

2017-04-15 23:39 UTC, don-smith commented on react/lifecycle-methods.md
> +When we're defining a component in React, we know that at least two methods are required: `constructor(props)`, and `render()`.
"When defining a stateful component in React, at least two methods are required: `constructor(props)` and `render()`.

2017-04-15 23:39 UTC, don-smith commented on react/lifecycle-methods.md
> +  - `componentWillUnmount` - before unmount
Haha ... this was probably me. Intuitively, the linux command to mount a drive is `mount`. Unintuitively, to unmount a drive, the command is `umount`. Now it's in my muscle memory to misspell unmount 😞 😆

2017-04-15 23:39 UTC, don-smith commented on react/lifecycle.md
> +* `componentWillUpdate` is invoked before rendering when new props or state is being received.
I'm not going to claim responsibility for this one though 😉

2017-04-15 23:39 UTC, don-smith commented on react/props.md
> +class Header extends React.Component {
`export default class ...`?

2017-04-15 23:39 UTC, don-smith commented on react/state.md
> +- **Props** is data **passed down** from a parent Component and should not be changed.
What about: **Props** is data **passed into** a Component from its parent and should not be changed.

2017-04-15 23:39 UTC, don-smith commented on react/state.md
> +- **State** is data created **within** a React Component and can be changed within a component using `this.setState()`
Instead of "**State** is data created **within** a ...", what about "**State** is data **created within** a ..."?

2017-04-15 23:39 UTC, don-smith commented on react/jsx.md
> +      <input type="text" name="input"> // Doesn't self close
Also, are we going to use double-quotes in JSX? My linter complains that I'm not using single-quotes.

2017-04-16 21:35 UTC, tony-luisi commented on react/components.md
> +export default Header
As discussed, will leave as is.

2017-04-16 22:05 UTC, tony-luisi commented on react/event-delegation.md
> +In order to respond to user events, component functions can be bound to [virtual ] DOM events. In this example, a `addToCart` function in the `<ItemList />` component is called when a button is click
updated

2017-04-16 22:05 UTC, tony-luisi commented on react/jsx.md
> +JSX is a syntax extension to javascript which can be thought of as a hybrid between HTML and javascript:
updated

2017-04-17 01:52 UTC, tony-luisi commented on react/jsx.md
> +      <input type="text" name="input"> // Doesn't self close
Updated self-close and to single quotes

2017-04-17 01:53 UTC, tony-luisi commented on react/lifecycle-methods.md
> +When we're defining a component in React, we know that at least two methods are required: `constructor(props)`, and `render()`.
Updated

2017-04-17 01:55 UTC, tony-luisi commented on react/lifecycle-methods.md
> +  - `componentWillUnmount` - before unmount
Lol!

2017-04-17 01:56 UTC, tony-luisi commented on react/lifecycle.md
> +* `componentWillUpdate` is invoked before rendering when new props or state is being received.
Easy mistake to make! My spell checker helped with that one.. not me. 😝

2017-04-17 01:57 UTC, tony-luisi commented on react/props.md
> +class Header extends React.Component {
As discussed, i've kept this at the bottom as `export default Header`

2017-04-17 01:58 UTC, tony-luisi commented on react/state.md
> +- **State** is data created **within** a React Component and can be changed within a component using `this.setState()`
updated

2017-04-17 01:58 UTC, tony-luisi commented on react/state.md
> +- **Props** is data **passed down** from a parent Component and should not be changed.
updated

2017-04-17 01:59 UTC, tony-luisi commented
I've made those changes as requested 😄

2017-04-17 02:10 UTC, don-smith approved these changes
Awesome!!

2017-04-17 02:10 UTC, merged